/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saleh
 */
public class UpdateProducts extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProducts
     */
    public UpdateProducts() {
        initComponents();
        try {
            showtable();
            
        } catch (SQLException ex) {
            Logger.getLogger(UpdateProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllProductsTable = new javax.swing.JTable();
        SearchBox = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updtBtn = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        quantity = new javax.swing.JSpinner();
        price = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 100));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(29, 31, 47));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBTN.setBackground(new java.awt.Color(29, 31, 47));
        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/undo.png"))); // NOI18N
        backBTN.setMaximumSize(new java.awt.Dimension(58, 32));
        backBTN.setMinimumSize(new java.awt.Dimension(58, 32));
        backBTN.setPreferredSize(new java.awt.Dimension(58, 32));
        backBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBTNMouseClicked(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        name.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Update Products");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 10, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(910, 700));

        AllProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Sub-Category", "Brand", "Type", "Quantity", "Warranty(Years)", "Price(BDT)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AllProductsTable.setName(""); // NOI18N
        AllProductsTable.setOpaque(false);
        AllProductsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(AllProductsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        SearchBox.setBackground(new java.awt.Color(255, 255, 255));
        SearchBox.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        SearchBox.setForeground(new java.awt.Color(102, 102, 102));
        SearchBox.setText("Search here...");
        SearchBox.setPreferredSize(new java.awt.Dimension(300, 45));
        SearchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBoxFocusLost(evt);
            }
        });
        jPanel1.add(SearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        SearchBtn.setBackground(new java.awt.Color(29, 31, 47));
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N
        SearchBtn.setPreferredSize(new java.awt.Dimension(40, 45));
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        jPanel1.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Quantity :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Price      :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        updtBtn.setBackground(new java.awt.Color(29, 31, 47));
        updtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updated2.png"))); // NOI18N
        updtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updtBtnMouseClicked(evt);
            }
        });
        jPanel1.add(updtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 510, -1, -1));

        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setText("Copyright © 2021, TechnoBot BD");
        jPanel1.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 700, -1, -1));

        quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quantity.setMinimumSize(new java.awt.Dimension(26, 24));
        quantity.setPreferredSize(new java.awt.Dimension(96, 24));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        price.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        price.setMinimumSize(new java.awt.Dimension(26, 24));
        price.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void backBTNMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setLocationRelativeTo(null);
        hp.setVisible(true);
        this.dispose();
    }                                    

    private void SearchBoxFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if(SearchBox.getText().equals("Search here...")){
            SearchBox.setText("");
            SearchBox.requestFocus();
            SearchBox.setForeground(new Color(0,0,0));
        }
    }                                     

    private void SearchBoxFocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        if(SearchBox.getText().length()== 0){
            SearchBox.setText("Search here...");
            SearchBox.setForeground(new Color(102,102,102));
        }
    }                                   

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        if(SearchBox.getText().length()== 0 || SearchBox.getText().equals("Search here...")){
            JOptionPane.showMessageDialog(null, "Invalid input", "Caution", JOptionPane.OK_OPTION);
        }
        else{
            try {
                searchtable();
            } catch (SQLException ex) {
                Logger.getLogger(AllProducts.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }                                      

    private void updtBtnMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if(AllProductsTable.getModel().getRowCount()>1 || AllProductsTable.getModel().getRowCount()<1){
            JOptionPane.showMessageDialog(null, "Please Search for the Product \n That you want to UPDATE", "Caution", JOptionPane.OK_OPTION);
        }
        else{
            checkupdate();
            clear();
            try {
                showtable();
            } catch (SQLException ex) {
                Logger.getLogger(UpdateProducts.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                    
    
    
    public void showtable()throws SQLException{
        String url ="jdbc:sqlserver://KAMI\\SQLEXPRESS:1433;databaseName=TECHNOBOT";
        String user = "sa";
        String password = "123456789";
        try{
            Connection conn = DriverManager.getConnection(url, user, password);
            
            AllProductsTable.setModel(new DefaultTableModel(null, new String [] {"Product ID", "Product Name", "Category", "Sub-Category", "Brand", "Type", "Quantity", "Warranty(Years)", "Price(BDT)"}));
            
            String sql = "Select * From PRODUCTS";
            
            Statement st = conn.createStatement();
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String pid = rs.getString("PRODUCT_ID");
                String pname = rs.getString("PRODUCT_NAME");
                String cat = rs.getString("CAT_NAME");
                String subcat = rs.getString("SUB_CAT_NAME");
                String bra = rs.getString("BRAND_NAME");
                String ptype = rs.getString("PRODUCT_TYPE");
                String qt = String.valueOf(rs.getInt("QUANTITY"));
                String wr = String.valueOf(rs.getInt("WARRANTY"));
                String prc = String.valueOf(rs.getInt("PRICE"));
                
                String tbdata[] = {pid,pname,cat,subcat,bra,ptype,qt,wr,prc};
                
                DefaultTableModel apt =  (DefaultTableModel) AllProductsTable.getModel();
                apt.addRow(tbdata);
            }
            conn.close();
        }catch(SQLException e){
            System.out.println("ERROR");
        }
    }
    
    public void searchtable()throws SQLException{
        String url ="jdbc:sqlserver://KAMI\\SQLEXPRESS:1433;databaseName=TECHNOBOT";
        String user = "sa";
        String password = "123456789";
        try{
            Connection conn = DriverManager.getConnection(url, user, password);
            
            String srch = SearchBox.getText();
            
            AllProductsTable.setModel(new DefaultTableModel(null, new String [] {"Product ID", "Product Name", "Category", "Sub-Category", "Brand", "Type", "Quantity", "Warranty(Years)", "Price(BDT)"}));
            
            //String sql = "Select * From PRODUCTS";
            
            //Statement st = conn.createStatement();
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM PRODUCTS WHERE PRODUCT_ID = ?");
            pst.setString(1, srch);
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String pid = rs.getString("PRODUCT_ID");
                String pname = rs.getString("PRODUCT_NAME");
                String cat = rs.getString("CAT_NAME");
                String subcat = rs.getString("SUB_CAT_NAME");
                String bra = rs.getString("BRAND_NAME");
                String ptype = rs.getString("PRODUCT_TYPE");
                String qt = String.valueOf(rs.getInt("QUANTITY"));
                int qnt = rs.getInt("QUANTITY");
                String wr = String.valueOf(rs.getInt("WARRANTY"));
                String prc = String.valueOf(rs.getInt("PRICE"));
                int pr = rs.getInt("PRICE");
                
                
                String tbdata[] = {pid,pname,cat,subcat,bra,ptype,qt,wr,prc};
                
                DefaultTableModel apt =  (DefaultTableModel) AllProductsTable.getModel();
                apt.addRow(tbdata);
                
                quantity.setValue(qnt);
                price.setValue(pr);
            }
            conn.close();
        }catch(SQLException e){
            System.out.println(e);
            System.out.println("ERROR");
        }
    }
    
    public void checkupdate(){
        if(quantity.getValue().equals(0) && price.getValue().equals(0)){
            confirmUpdate1();
        }
        else if(quantity.getValue().equals(0)){
            confirmUpdate2();
        }
        else if(price.getValue().equals(0)){
            confirmUpdate3();
        }
        else{
            updateproduct();
            JOptionPane.showMessageDialog(null, "Successfully Updated", "Successs", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void confirmUpdate1(){
        int confirm = JOptionPane.showConfirmDialog(null,"Sure? You want to Update both values to 0?", "Caution",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            try{
                updateproduct();
                JOptionPane.showMessageDialog(null, "Successfully Updated", "Successs", JOptionPane.INFORMATION_MESSAGE);
                    
            }catch(Exception e){
                System.out.println("ERROR");
            }   
        }
    }
    public void confirmUpdate2(){
        int confirm = JOptionPane.showConfirmDialog(null,"Sure? You want to Update Quantity to 0?", "Caution",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            try{
                updateproduct();
                JOptionPane.showMessageDialog(null, "Successfully Updated", "Successs", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                System.out.println("ERROR");
            }   
        }
    }
    public void confirmUpdate3(){
        int confirm = JOptionPane.showConfirmDialog(null,"Sure? You want to Update Price to 0?", "Caution",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
            try{
                updateproduct();
                JOptionPane.showMessageDialog(null, "Successfully Updated", "Successs", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                System.out.println("ERROR");
            }   
        }
    }
    
    public void updateproduct(){
        String url ="jdbc:sqlserver://KAMI\\SQLEXPRESS:1433;databaseName=TECHNOBOT";
        String user = "sa";
        String password = "123456789";
        try{
            Connection conn = DriverManager.getConnection(url, user, password);
            
            int qt = (Integer) quantity.getValue();
            int prc = (Integer) price.getValue();
            String srch = SearchBox.getText();
            //String sql = "Select * From SUBCATEGORY Where CAT_NAME = " " Order By SUB_CAT_ID";
            
            PreparedStatement pst = conn.prepareStatement("Update PRODUCTS Set QUANTITY = ? , PRICE = ? WHERE PRODUCT_ID = ?");
            pst.setInt(1, qt);
            pst.setInt(2, prc);
            pst.setString(3, srch);
            
            //Statement st = conn.createStatement();
            
            //ResultSet rs = pst.executeQuery();
            
            int rows = pst.executeUpdate();

            if (rows > 0) {
                System.out.println("Product updated");
            }
            
            conn.close();
        }catch(SQLException e){
            System.out.println("ERROR");
        }
    }
    
    public void clear(){
        SearchBox.setText("Search here...");
        SearchBox.setForeground(new Color(102,102,102));
        quantity.setValue(0);
        price.setValue(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateProducts up = new UpdateProducts();
                up.setLocationRelativeTo(null);
                up.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable AllProductsTable;
    private javax.swing.JTextField SearchBox;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JSpinner price;
    private javax.swing.JSpinner quantity;
    private javax.swing.JButton updtBtn;
    // End of variables declaration                   
}
